FB test

diff --git a/.github/workflows/merging_PR_test.yml b/.github/workflows/merging_PR_test.yml
--- a/.github/workflows/merging_PR_test.yml
+++ b/.github/workflows/merging_PR_test.yml
@@ -1,4 +1,4 @@
-name: OpenLogin - New V2 User Login
+name: OpenLogin - Facebook Login
 
 on:
   push
@@ -8,34 +8,25 @@ on:
 
 env:
   NODE_VERSION: 16
-  LOCAL_PATH: openlogin/new-v2-user-login
-  S3_PATH: openlogin/new-v2-user-login
 
 jobs:
   run-tests:
-    name: Run OpenLogin - New V2 User Login tests
+    name: Run OpenLogin - Facebook Login tests
     strategy:
       # matrix:
-      #   os: [macos-latest]
-      #   browser: [chromium]
-      #   local_path: [openlogin/new-v2-user-login]
-      #   s3_path: [openlogin/new-v2-user-login]
-      #   env: [PROD, STAGING, CYAN]
+      #   include:
+      #     - browser: chromium
+      #       os: windows-latest
+      #     - browser: firefox
+      #       os: windows-latest
       matrix:
         env: [prod]
         browser: [firefox, chromium, webkit]
         os: [macos-latest, windows-latest, ubuntu-latest]
-        include:
-          - os: macos-latest
-            browser: chromium
-            env: cyan
-          - os: macos-latest
-            browser: chromium
-            env: beta
 
     runs-on: ${{ matrix.os }}
-    env:
-      PLATFORM: ${{ matrix.env }}
+    outputs:
+      conclusion: ${{ steps.run-tests.conclusion }}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -70,28 +61,16 @@ jobs:
           aws-region: us-east-1
         continue-on-error: true
 
-      # - name: Set Path
-      #   run: |
-      #     if [[ ${{ matrix.env }} != 'prod' ]]
-      #     then
-      #         echo "S3_PATH=${{ env.LOCAL_PATH }}-${{ matrix.env }}" >> $GITHUB_ENV
-      #     else
-      #         echo "S3_PATH=${{ env.LOCAL_PATH }}" >> $GITHUB_ENV
-      #     fi
-      #   shell: bash
-
       - id: download-state
         name: Download remote browser snapshots
         if: steps.configure-aws.outcome == 'success'
-        run: aws s3 cp s3://torus-e2e-tests/${{ env.S3_PATH }}/ ${{ env.LOCAL_PATH }}/ --recursive
+        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-facebook/ openlogin/login-with-facebook/ --recursive
         continue-on-error: true
 
       - id: run-tests
         name: Run tests
-        env:
-          TEST_RUN_ID: ${{ matrix.os }}.${{ matrix.browser }}.${{ github.run_id }}.${{ github.run_attempt }}
         if: steps.download-state.outcome == 'success'
-        run: yarn run playwright test --config ${{ env.LOCAL_PATH }}/index.config.ts --project ${{ matrix.browser }}
+        run: yarn run playwright test --config openlogin/login-with-facebook/index.config.ts --project ${{ matrix.browser }}
 
       # - id: telegram-alert
       #   name: Alert to telegram channel
@@ -100,24 +79,11 @@ jobs:
       #     if [[ ${{ steps.run-tests.outcome }} != 'success' ]]
       #     then
       #         echo "Test Failed, sending telegram alert"
-      #         curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginWithNewV2User%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}%0AEnvironment=${{matrix.env}}%0AJob=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
+      #         curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginWithFacebook%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}%0AEnvironment=${{matrix.env}}%0AJob=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
       #     else
       #         echo "Test Passed, no alert!"
       #     fi
       #   continue-on-error: true
-
-      - id: upload-state
-        name: Upload logged-in state once a week
-        uses: ./.github/actions/upload-state/
-        with:
-          os: ${{ matrix.os }}
-          browser: ${{ matrix.browser }}
-          s3_path: ${{ env.S3_PATH }}
-          local_path: ${{ env.LOCAL_PATH }}
-          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-east-1
-        continue-on-error: true
 
       - name: Upload test results
         if: always()
@@ -126,3 +92,20 @@ jobs:
           name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
           path: test-results/
           if-no-files-found: ignore
+
+  # update-status:
+  #   name: Update OpenLogin - Facebook Login status
+  #   needs: run-tests
+  #   if: (success() || failure()) && (needs.run-tests.outputs.conclusion != 'skipped')
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.FACEBOOK_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: "application/json"
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
