passwordless test to use strategy matrix

diff --git a/.github/workflows/openlogin.login-with-passwordless-cyan.yml b/.github/workflows/openlogin.login-with-passwordless-cyan.yml
--- a/.github/workflows/openlogin.login-with-passwordless-cyan.yml
+++ b/.github/workflows/openlogin.login-with-passwordless-cyan.yml
@@ -1,22 +1,31 @@
-name: OpenLogin - Passwordless Login- CYAN
+name: OpenLogin - Passwordless Login
 
 on:
-  schedule:
-    - cron: "*/15 * * * *"
-  workflow_dispatch:
+  push
+  # schedule:
+  #   - cron: "*/15 * * * *"
+  # workflow_dispatch:
 
 env:
   NODE_VERSION: 16
-  PLATFORM: CYAN
 
 jobs:
   run-tests:
-    name: Run OpenLogin - Passwordless Login tests- CYAN
+    name: Run OpenLogin - Passwordless Login tests
     strategy:
       matrix:
+        os: [macos-latest]
+        browser: [firefox]
+        local_path: [openlogin/login-with-passwordless]
+        env: [PROD, STAGING, CYAN]
         include:
-          - browser: firefox
-            os: macos-latest
+          - s3_path: openlogin/login-with-passwordless
+            env: PROD
+          - s3_path: openlogin/login-with-passwordless-cyan
+            env: CYAN
+          - s3_path: openlogin/login-with-passwordless-beta
+            env: STAGING
+
     runs-on: ${{ matrix.os }}
     outputs:
       conclusion: ${{ steps.run-tests.conclusion }}
@@ -57,13 +66,19 @@ jobs:
       - id: download-state
         name: Download remote browser snapshots
         if: steps.configure-aws.outcome == 'success'
-        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless-cyan/ openlogin/login-with-passwordless/ --recursive
+        run: aws s3 cp s3://torus-e2e-tests/${{ matrix.s3_path }}/ ${{ matrix.local_path }}/ --recursive
         continue-on-error: true
 
       - id: run-tests
         name: Run tests
         if: steps.download-state.outcome == 'success'
-        run: yarn run playwright test --config openlogin/login-with-passwordless/index.config.ts --project ${{ matrix.browser }}
+        run: yarn run playwright test --config ${{ matrix.local_path }}/index.config.ts --project ${{ matrix.browser }}
+
+      # - id: telegram-alert
+      #   name: Alert to telegram channel
+      #   if: steps.run-tests.outcome != 'success'
+      #   run: curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginPasswordless%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}"
+      #   continue-on-error: true
 
       - id: upload-state
         name: Upload logged-in state once a week
@@ -71,8 +86,8 @@ jobs:
         with:
           os: ${{ matrix.os }}
           browser: ${{ matrix.browser }}
-          s3_path: openlogin/login-with-passwordless-cyan
-          local_path: openlogin/login-with-passwordless
+          s3_path: ${{ matrix.s3_path }}
+          local_path: ${{ matrix.local_path }}
           aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws_region: us-east-1
@@ -86,3 +101,19 @@ jobs:
           path: test-results/
           if-no-files-found: ignore
 
+  # update-status:
+  #   name: Update OpenLogin - Passwordless Login status
+  #   needs: run-tests
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: "application/json"
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
diff --git a/.github/workflows/openlogin.login-with-passwordless.yml b/.github/workflows/openlogin.login-with-passwordless.yml
--- a/.github/workflows/openlogin.login-with-passwordless.yml
+++ b/.github/workflows/openlogin.login-with-passwordless.yml
@@ -13,9 +13,18 @@ jobs:
     name: Run OpenLogin - Passwordless Login tests
     strategy:
       matrix:
+        os: [macos-latest]
+        browser: [firefox]
+        local_path: [openlogin/login-with-passwordless]
+        env: [PROD, STAGING, CYAN]
         include:
-          - browser: firefox
-            os: macos-latest
+          - s3_path: openlogin/login-with-passwordless
+            env: PROD
+          - s3_path: openlogin/login-with-passwordless-cyan
+            env: CYAN
+          - s3_path: openlogin/login-with-passwordless-beta
+            env: STAGING
+
     runs-on: ${{ matrix.os }}
     outputs:
       conclusion: ${{ steps.run-tests.conclusion }}
@@ -56,34 +65,31 @@ jobs:
       - id: download-state
         name: Download remote browser snapshots
         if: steps.configure-aws.outcome == 'success'
-        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless/ openlogin/login-with-passwordless/ --recursive
+        run: aws s3 cp s3://torus-e2e-tests/${{ matrix.s3_path }}/ ${{ matrix.local_path }}/ --recursive
         continue-on-error: true
 
       - id: run-tests
         name: Run tests
         if: steps.download-state.outcome == 'success'
-        run: yarn run playwright test --config openlogin/login-with-passwordless/index.config.ts --project ${{ matrix.browser }}
+        run: yarn run playwright test --config ${{ matrix.local_path }}/index.config.ts --project ${{ matrix.browser }}
 
-      - id: telegram-alert
-        name: Alert to telegram channel
-        if: steps.run-tests.outcome != 'success'
-        run: curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginPasswordless%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}"
-        continue-on-error: true
+      # - id: telegram-alert
+      #   name: Alert to telegram channel
+      #   if: steps.run-tests.outcome != 'success'
+      #   run: curl "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage?chat_id=${{secrets.CHAT_ID}}&text=LoginPasswordless%0ATestresult=Failed%0AOS=${{matrix.os}}%0Abrowser=${{matrix.browser}}"
+      #   continue-on-error: true
 
       - id: upload-state
-        name: Upload logged-in state once a day
-        run: |
-          last_updated=$(aws s3 ls s3://torus-e2e-tests/openlogin/login-with-passwordless/${{ matrix.browser }}.json | awk '{print $1}')
-          yesterday=$(date -v-1d +'%Y-%m-%d')
-          echo "Last Updated: $last_updated, Yesterday: $yesterday"
-
-          if [[ "$last_updated" > "$yesterday" ]]
-          then
-              echo "State is still new, no need to update"
-          else
-              echo "State is old, need to refresh"
-              aws s3 cp openlogin/login-with-passwordless/${{ matrix.browser }}.json s3://torus-e2e-tests/openlogin/login-with-passwordless/
-          fi
+        name: Upload logged-in state once a week
+        uses: ./.github/actions/upload-state/
+        with:
+          os: ${{ matrix.os }}
+          browser: ${{ matrix.browser }}
+          s3_path: ${{ matrix.s3_path }}
+          local_path: ${{ matrix.local_path }}
+          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws_region: us-east-1
         continue-on-error: true
 
       - name: Upload test results
@@ -94,19 +100,19 @@ jobs:
           path: test-results/
           if-no-files-found: ignore
 
-  update-status:
-    name: Update OpenLogin - Passwordless Login status
-    needs: run-tests
-    if: success() || failure()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Update status
-        uses: fjogeleit/http-request-action@master
-        with:
-          url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
-          customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
-          method: PATCH
-          contentType: "application/json"
-          timeout: 10000
-          data: >-
-            { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
+  # update-status:
+  #   name: Update OpenLogin - Passwordless Login status
+  #   needs: run-tests
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: "application/json"
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
