feat: fixed broken passwordless login test

diff --git a/.github/workflows/openlogin.login-with-passwordless.yml b/.github/workflows/openlogin.login-with-passwordless.yml
--- a/.github/workflows/openlogin.login-with-passwordless.yml
+++ b/.github/workflows/openlogin.login-with-passwordless.yml
@@ -59,11 +59,26 @@ jobs:
         run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless/ openlogin/login-with-passwordless/ --recursive
         continue-on-error: true
 
-      # TODO: Uncomment this to run tests
-      # - id: run-tests
-      #   name: Run tests
-      #   if: steps.download-state.outcome == 'success
-      #   run: yarn run playwright test --config openlogin/login-with-passwordless/index.config.ts --project ${{ matrix.browser }}
+      TODO: Uncomment this to run tests
+      - id: run-tests
+        name: Run tests
+        if: steps.download-state.outcome == 'success
+        run: yarn run playwright test --config openlogin/login-with-passwordless/index.config.ts --project ${{ matrix.browser }}
+
+      - id: upload-state
+        name: Upload logged-in state once a day
+        run: |
+          last_updated=$(aws s3 ls s3://torus-e2e-tests/openlogin/login-with-passwordless/${{ matrix.browser }}.json | awk '{print $1}')
+          yesterday=$(date -v-1d +'%Y-%m-%d')
+          echo "Last Updated: $last_updated, Yesterday: $yesterday"
+
+          if [[ "$last_updated" > "$yesterday" ]]
+          then
+              echo "State is still new, no need to update"
+          else
+              echo "State is old, need to refresh"
+              aws s3 cp openlogin/login-with-passwordless/${{ matrix.browser }}.json s3://torus-e2e-tests/openlogin/login-with-passwordless/
+          fi
 
       - name: Upload test results
         if: always()
@@ -73,19 +88,19 @@ jobs:
           path: test-results/
           if-no-files-found: ignore
 
-  update-status:
-    name: Update OpenLogin - Passwordless Login status
-    needs: run-tests
-    if: success() || failure()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Update status
-        uses: fjogeleit/http-request-action@master
-        with:
-          url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
-          customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
-          method: PATCH
-          contentType: 'application/json'
-          timeout: 10000
-          data: >-
-            { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
+  # update-status:
+  #   name: Update OpenLogin - Passwordless Login status
+  #   needs: run-tests
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: 'application/json'
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
