added passwordless test

diff --git a/.github/workflows/openlogin.login-with-passwordless-beta.yml b/.github/workflows/openlogin.login-with-passwordless-beta.yml
--- a/.github/workflows/openlogin.login-with-passwordless-beta.yml
+++ b/.github/workflows/openlogin.login-with-passwordless-beta.yml
@@ -1,17 +1,18 @@
-name: OpenLogin - Passwordless Login
+name: OpenLogin - Passwordless Login- BETA
 
 on:
-  schedule:
-    - cron: "*/15 * * * *"
-  workflow_dispatch:
+  push
+  # schedule:
+  #   - cron: "*/15 * * * *"
+  # workflow_dispatch:
 
 env:
   NODE_VERSION: 16
-  PLATFORM: PROD
+  PLATFORM: STAGING
 
 jobs:
   run-tests:
-    name: Run OpenLogin - Passwordless Login tests
+    name: Run OpenLogin - Passwordless Login tests- BETA
     strategy:
       matrix:
         include:
@@ -57,7 +58,7 @@ jobs:
       - id: download-state
         name: Download remote browser snapshots
         if: steps.configure-aws.outcome == 'success'
-        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless/ openlogin/login-with-passwordless/ --recursive
+        run: aws s3 cp s3://torus-e2e-tests/openlogin/login-with-passwordless-beta/ openlogin/login-with-passwordless/ --recursive
         continue-on-error: true
 
       - id: run-tests
@@ -68,7 +69,7 @@ jobs:
       - id: upload-state
         name: Upload logged-in state once a day
         run: |
-          last_updated=$(aws s3 ls s3://torus-e2e-tests/openlogin/login-with-passwordless/${{ matrix.browser }}.json | awk '{print $1}')
+          last_updated=$(aws s3 ls s3://torus-e2e-tests/openlogin/login-with-passwordless-beta/${{ matrix.browser }}.json | awk '{print $1}')
           yesterday=$(date -v-1d +'%Y-%m-%d')
           echo "Last Updated: $last_updated, Yesterday: $yesterday"
 
@@ -77,7 +78,7 @@ jobs:
               echo "State is still new, no need to update"
           else
               echo "State is old, need to refresh"
-              aws s3 cp openlogin/login-with-passwordless/${{ matrix.browser }}.json s3://torus-e2e-tests/openlogin/login-with-passwordless/
+              aws s3 cp openlogin/login-with-passwordless/${{ matrix.browser }}.json s3://torus-e2e-tests/openlogin/login-with-passwordless-beta/
           fi
         continue-on-error: true
 
@@ -89,19 +90,19 @@ jobs:
           path: test-results/
           if-no-files-found: ignore
 
-  update-status:
-    name: Update OpenLogin - Passwordless Login status
-    needs: run-tests
-    if: success() || failure()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Update status
-        uses: fjogeleit/http-request-action@master
-        with:
-          url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
-          customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
-          method: PATCH
-          contentType: "application/json"
-          timeout: 10000
-          data: >-
-            { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
+  # update-status:
+  #   name: Update OpenLogin - Passwordless Login status
+  #   needs: run-tests
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.PASSWORDLESS_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: "application/json"
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
