google test beta

diff --git a/.github/workflows/openlogin.login-with-google-beta.yml b/.github/workflows/openlogin.login-with-google-beta.yml
--- a/.github/workflows/openlogin.login-with-google-beta.yml
+++ b/.github/workflows/openlogin.login-with-google-beta.yml
@@ -66,17 +66,21 @@ jobs:
         if: steps.download-state.outcome == 'success'
         run: yarn run playwright test --config openlogin/login-with-google/index.config.ts --project ${{ matrix.browser }}
 
-      # - id: upload-state
-      #   name: Upload logged-in state once a week
-      #   uses: ./.github/actions/upload-state/
-      #   with:
-      #     os: ${{ matrix.os }}
-      #     browser: ${{ matrix.browser }}
-      #     path: openlogin/login-with-google
-      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     aws_region: us-east-1
-      #   continue-on-error: true
+      - id: upload-state
+        name: Upload logged-in state once a day
+        run: |
+          last_updated=$(aws s3 ls s3://torus-e2e-tests/openlogin/login-with-google-beta/${{ matrix.browser }}.json | awk '{print $1}')
+          yesterday=$(date -v-1d +'%Y-%m-%d')
+          echo "Last Updated: $last_updated, Yesterday: $yesterday"
+
+          if [[ "$last_updated" > "$yesterday" ]]
+          then
+              echo "State is still new, no need to update"
+          else
+              echo "State is old, need to refresh"
+              aws s3 cp openlogin/login-with-google/${{ matrix.browser }}.json s3://torus-e2e-tests/openlogin/login-with-google-beta/
+          fi
+        continue-on-error: true
 
       - name: Upload test results
         if: always()
@@ -85,3 +89,20 @@ jobs:
           name: test-results-on-${{ matrix.browser }}-${{ matrix.os }}
           path: test-results/
           if-no-files-found: ignore
+
+  # update-status:
+  #   name: Update OpenLogin - Google Login status
+  #   needs: run-tests
+  #   if: (success() || failure()) && (needs.run-tests.outputs.conclusion != 'skipped')
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Update status
+  #       uses: fjogeleit/http-request-action@master
+  #       with:
+  #         url: https://api.statuspage.io/v1/pages/${{ secrets.PAGE_ID }}/components/${{ secrets.GOOGLE_COMPONENT_ID }}
+  #         customHeaders: '{ "Authorization": "OAuth ${{ secrets.STATUS_PAGE_API_KEY }}" }'
+  #         method: PATCH
+  #         contentType: "application/json"
+  #         timeout: 10000
+  #         data: >-
+  #           { "component": { "status": "${{ needs.run-tests.result == 'success' && 'operational' || 'major_outage' }}" } }
